title: Junior Web Developer
author: Delphine Bararwandika
email: mdelphy@gmail.com
description: 

# social links
LinkedIn_username: www.linkedin.com/in/delphine-bararwandika-219149bb
github_username:  D-bararwandika

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
